=== bhaddad5/CRGame/Assets/StreamingAssets/XmlSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="XMLSchema" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" >

	<xs:element name="GameData" type="GameData"/>

	<xs:complexType name="Effect">
		<xs:attribute name="ContextualFemId" type="xs:string"/>
		<xs:attribute name="AmbitionEffect" type="xs:float"/>
		<xs:attribute name="PrideEffect" type="xs:float"/>
		<xs:attribute name="EgoEffect" type="xs:float"/>
		<xs:attribute name="FundsEffect" type="xs:float"/>
		<xs:attribute name="PowerEffect" type="xs:float"/>
		<xs:attribute name="PatentsEffect" type="xs:float"/>
		<xs:attribute name="CultureEffect" type="xs:float"/>
		<xs:attribute name="SpreadsheetsEffect" type="xs:float"/>
		<xs:attribute name="BrandEffect" type="xs:float"/>
		<xs:attribute name="RevanueEffect" type="xs:float"/>
		<xs:attribute name="HornicalEffect" type="xs:int"/>
		<xs:attribute name="ControlEffect" type="xs:boolean"/>
		<xs:attribute name="RemoveNpcFromGame" type="xs:boolean"/>
		<xs:attribute name="TraitsAdded" type="xs:string"/>
		<xs:attribute name="TraitsRemoved" type="xs:string"/>
		<xs:attribute name="TrophiesClaimed" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="DialogEntry">
		<xs:attribute name="Speaker" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Player"/>
					<xs:enumeration value="Fem"/>
					<xs:enumeration value="Narrator"/>
					<xs:enumeration value="CustomFemId"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="CustomSpeakerId" type="xs:string"/>
		<xs:attribute name="Dialog" type="xs:string" use="required"/>
		<xs:attribute name="NpcImage" type="xs:string"/>
		<xs:attribute name="InPlayerOffice" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="Popup">
		<xs:attribute name="Title" type="xs:string"/>
		<xs:attribute name="Text" type="xs:string" use="required"/>
		<xs:attribute name="Image" type="xs:string"/>
		<xs:attribute name="Video" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="InteractionResult">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="DialogEntry" type="DialogEntry"/>
			</xs:choice>
			<xs:choice maxOccurs="1" minOccurs="0">
				<xs:element name="Popup" type="Popup"/>
			</xs:choice>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element name="Effect" type="Effect"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Cost">
		<xs:attribute name="TurnCost" type="xs:decimal"/>
		<xs:attribute name="EgoCost" type="xs:float"/>
		<xs:attribute name="MoneyCost" type="xs:float"/>
		<xs:attribute name="PatentsCost" type="xs:float"/>
		<xs:attribute name="CultureCost" type="xs:float"/>
		<xs:attribute name="SpreadsheetsCost" type="xs:float"/>
		<xs:attribute name="BrandCost" type="xs:float"/>
		<xs:attribute name="RevanueCost" type="xs:float"/>
		<xs:attribute name="HornicalCost" type="xs:int"/>
	</xs:complexType>

	<xs:complexType name="Requirements">
		<xs:attribute name="RequiredDepartmentsControlled" type="xs:string"/>
		<xs:attribute name="RequiredInteractions" type="xs:string"/>
		<xs:attribute name="RequiredPolicies" type="xs:string"/>
		<xs:attribute name="RequiredTrophies" type="xs:string"/>
		<xs:attribute name="RequiredPower" type="xs:float"/>
		<xs:attribute name="RequiredAmbition" type="xs:float"/>
		<xs:attribute name="RequiredPride" type="xs:float"/>
		<xs:attribute name="RequiredControl" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="Interaction">
		<xs:sequence>
			<xs:choice maxOccurs="1" minOccurs="1">
				<xs:element name="Cost" type="Cost"/>
			</xs:choice>
			<xs:choice maxOccurs="1" minOccurs="1">
				<xs:element name="Requirements" type="Requirements"/>
			</xs:choice>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element name="InteractionResult" type="InteractionResult"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Category" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="OfficePolitics"/>
					<xs:enumeration value="Conversation"/>
					<xs:enumeration value="Challenge"/>
					<xs:enumeration value="Socialize"/>
					<xs:enumeration value="Projects"/>
					<xs:enumeration value="Train"/>
					<xs:enumeration value="Fun"/>
					<xs:enumeration value="Surveillance"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Repeatable" type="xs:boolean"/>
		<xs:attribute name="Completed" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="Trait">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element name="FreeEffect" type="Effect"/>
			</xs:choice>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element name="ControlledEffect" type="Effect"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="Trophy">
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Image" type="xs:string" use="required"/>
		<xs:attribute name="Owned" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="Fem">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="Trait" type="Trait"/>
			</xs:choice>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="Trophy" type="Trophy"/>
			</xs:choice>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="Interaction" type="Interaction"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attribute name="FirstName" type="xs:string" use="required"/>
		<xs:attribute name="LastName" type="xs:string" use="required"/>
		<xs:attribute name="Age" type="xs:decimal" use="required"/>
		<xs:attribute name="Controlled" type="xs:boolean"/>
		<xs:attribute name="Ambition" type="xs:float"/>
		<xs:attribute name="Pride" type="xs:float"/>
		<xs:attribute name="BackgroundImage" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="Policy">
		<xs:sequence>
			<xs:choice maxOccurs="1" minOccurs="1">
				<xs:element name="Requirements" type="Requirements"/>
			</xs:choice>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element name="Effect" type="Effect"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="Image" type="xs:string" use="required"/>
		<xs:attribute name="Description" type="xs:string" use="required"/>
		<xs:attribute name="Active" type="xs:boolean"/>
	</xs:complexType>

	<xs:complexType name="Mission">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element name="Effect" type="Effect"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="MissionName" type="xs:string" use="required"/>
		<xs:attribute name="MissionDescription" type="xs:string" use="required"/>
		<xs:attribute name="MissionImage" type="xs:string" use="required"/>
		<xs:attribute name="FemId" type="xs:string" use="required"/>
		<xs:attribute name="InteractionId" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:complexType name="Department">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="Fem" type="Fem"/>
			</xs:choice>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="Policy" type="Policy"/>
			</xs:choice>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="Mission" type="Mission"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
		<xs:attribute name="ClosedOnWeekends" type="xs:boolean"/>
		<xs:attribute name="Accessible" type="xs:boolean"/>
		<xs:attribute name="UiPosX" type="xs:float" use="required"/>
		<xs:attribute name="UiPosY" type="xs:float" use="required"/>
		<xs:attribute name="BackgroundImage" type="xs:string" use="required"/>
		<xs:attribute name="LocationIcon" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="GameData">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded" minOccurs="0">
				<xs:element name="Department" type="Department"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="PlayerName" type="xs:string"/>
		<xs:attribute name="TurnNumber" type="xs:decimal"/>
		<xs:attribute name="Ego" type="xs:float"/>
		<xs:attribute name="Funds" type="xs:float"/>
		<xs:attribute name="Power" type="xs:float"/>
		<xs:attribute name="Patents" type="xs:float"/>
		<xs:attribute name="CorporateCulture" type="xs:float"/>
		<xs:attribute name="Spreadsheets" type="xs:float"/>
		<xs:attribute name="Brand" type="xs:float"/>
		<xs:attribute name="Revanue" type="xs:float"/>
		<xs:attribute name="Hornical" type="xs:int"/>
	</xs:complexType>
</xs:schema>

=== bhaddad5/CRGame/Assets/Resources/XmlData/GameData.xml
<GameData Actions="4" Ego="20" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com XmlSchema.xsd">
	<Department Id="legal" Name="Legal" Accessible="true" UiPosX="911" UiPosY="429">
		<Fem Id="deborahJones" Name="Deborah Jones" Age="24" Ambition="90" Pride="100">
			<Trait Id="overAchiever" Name="Over-Achiever">
				<Effect AmbitionEffect=".5" />
			</Trait>
			<Interaction Id="insinuatingComments" Name="Insinuating Comments - No wonder you got this job, with an ass like that...  I may have to smack it one of these days." EgoCost="10">
				<InteractionResult>
					<DialogEntry IsPlayer="true" Dialog="No wonder you got this job, with an ass like that...  I may have to smack it one of these days."/>
					<DialogEntry IsPlayer="false" Dialog="Noooooo..."/>
					<Effect AmbitionEffect="-20"/>
				</InteractionResult>
				<InteractionResult>
					<DialogEntry IsPlayer="true" Dialog="Hey baby..."/>
					<DialogEntry IsPlayer="false" Dialog="Fuck you!"/>
					<Effect AmbitionEffect="5"/>
				</InteractionResult>
			</Interaction>
			<Interaction Id="takeControl" Name="Take Control" RequiredAmbition="0">
				<InteractionResult>
					<DialogEntry IsPlayer="true" Dialog="I own you now."/>
					<DialogEntry IsPlayer="false" Dialog="OK Sempai..."/>
					<Effect EgoEffect="100" ControlEffect="true"/>
				</InteractionResult>
			</Interaction>
			<Interaction Id="motivationRoomApt" Name="Motivation Room Appointment" EgoCost="20" TurnCost="4" RequiredControl="true" RequiredPolicies="peaceOfMind">
				<InteractionResult>
					<DialogEntry IsPlayer="true" Dialog="I think your attitude needs correcting..."/>
					<DialogEntry IsPlayer="false" Dialog="Oh no!  Please don't spank me sir!"/>
					<Effect PrideEffect="-20"/>
				</InteractionResult>
			</Interaction>
		</Fem>
		<Policy Id="peaceOfMind" Name="Peace of Mind" Active="false"/>
	</Department>
</GameData>
